# Generated by Django 2.2.9 on 2020-04-28 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mail.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('prefix_d', models.CharField(max_length=25)),
                ('information', models.CharField(max_length=500)),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('body', models.CharField(blank=True, max_length=4000, null=True)),
                ('secrecy', models.IntegerField(choices=[(0, 'Несекретно'), (3, 'Для служебного пользования'), (2, 'Секретно'), (1, 'Совершенно Секретно')])),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=12)),
                ('first_name_d', models.CharField(max_length=12)),
                ('last_name_d', models.CharField(blank=True, max_length=12, null=True)),
                ('tolerance_level', models.IntegerField(blank=True, choices=[(0, 'Несекретно'), (3, 'Для служебного пользования'), (2, 'Секретно'), (1, 'Совершенно Секретно')], null=True)),
                ('activate', models.BooleanField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('admin', 'admin'), ('user', 'user'), ('redactor', 'redactor'), ('profile', 'profile')], max_length=12, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mail.Company')),
                ('host', models.ManyToManyField(blank=True, null=True, related_name='Пользователи_которым_доступна_почта', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Юзер', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('succes', 'succes'), ('error', 'error'), ('warning', 'warning')], max_length=40)),
                ('allowed_to_view', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=25, null=True)),
                ('viewed_by_user', models.BooleanField(default=False)),
                ('id_t', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Group_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime', models.DateTimeField(blank=True, default=mail.models.default_datetime, null=True)),
                ('answer_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.Group_message', verbose_name='ответ на  сообщение')),
                ('have_read', models.ManyToManyField(blank=True, related_name='dsds', to=settings.AUTH_USER_MODEL, verbose_name='Кто прочел')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mail.Message', verbose_name='Message')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otprav', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('profile', models.ManyToManyField(blank=True, null=True, related_name='profile', to='mail.Profile', verbose_name='Получатель из профилей')),
                ('received', models.ManyToManyField(blank=True, related_name='poluchili', to=settings.AUTH_USER_MODEL, verbose_name='Кто получил')),
                ('sending_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_essage', to='mail.Group_message', verbose_name='Ответ на')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Получатели почты')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('specificate', models.CharField(blank=True, choices=[('folder', 'folder'), ('trush', 'trush'), ('favorite', 'favorite'), ('send', 'send'), ('inbox', 'inbox')], default='folder', max_length=20, null=True, verbose_name='spec')),
                ('message', models.ManyToManyField(blank=True, null=True, to='mail.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_folder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('ps', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=25, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=mail.models.get_file_path)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Сообщение', to='mail.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Shablon_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=7000)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shablo', to=settings.AUTH_USER_MODEL, verbose_name='Shablon')),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
