# Generated by Django 2.2.1 on 2019-08-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='specificate',
            field=models.CharField(blank=True, choices=[('folder', 'folder'), ('trush', 'trush'), ('favorite', 'favorite')], default='folder', max_length=20, null=True, verbose_name='spec'),
        ),
    ]
