# Generated by Django 2.2.1 on 2019-07-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_to_message', to='mail.Message'),
        ),
    ]
