# Generated by Django 2.2.1 on 2019-07-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20190722_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='message',
        ),
        migrations.AddField(
            model_name='folder',
            name='message',
            field=models.ManyToManyField(to='mail.Message'),
        ),
    ]
