# Generated by Django 2.2.1 on 2019-07-27 09:35

from django.db import migrations, models
import mail.models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20190722_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='article_date',
        ),
        migrations.AlterField(
            model_name='group_message',
            name='lifetime',
            field=models.DateTimeField(blank=True, default=mail.models.default_datetime, null=True),
        ),
    ]
