# Generated by Django 2.2.1 on 2019-07-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20190727_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='message',
            field=models.ManyToManyField(blank=True, null=True, to='mail.Message'),
        ),
    ]
