# Generated by Django 2.2.1 on 2019-08-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20190731_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='specificate',
            field=models.CharField(blank=True, choices=[('folder', 'folder'), ('trush', 'trush'), ('favorite', 'favorite')], default='folder', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Сообщение', to='mail.Message'),
        ),
    ]
