# Generated by Django 2.2.1 on 2019-08-14 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20190813_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_folder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group_message',
            name='have_read',
            field=models.ManyToManyField(blank=True, related_name='dsds', to=settings.AUTH_USER_MODEL, verbose_name='Кто прочел'),
        ),
        migrations.AlterField(
            model_name='group_message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otprav', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='group_message',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Получатели почты'),
        ),
    ]
